### ISSUE TITLE
Receiving Multiple Notifications

### ISSUE THREAD

**Issue by shape-err** [Palleri/dockcheck-slim#2]
I've setup notifications to be pushed out through Signal. Instead of just 1 message per day I'm receiving 4 at once. When restarting the container, the first initial message sends out only 1. It's not until the next check is when 4 are sent, then I receive the error message below.

```
Starting Dockcheck-web
Checking for new updates
This might take a while, it depends on how many containers are running #
Notify activated
rm: can't remove '/app/notifymsg': No such file or directory
rm: can't remove '/app/notifymsg': No such file or directory
rm: can't remove '/app/notifymsg': No such file or directory
rm: can't remove '/app/notifymsg': No such file or directory
rm: can't remove '/app/notifymsg': No such file or directory
rm: can't remove '/app/notifymsg': No such file or directory
```
![signal-2023-03-11-130236_002](https://user-images.githubusercontent.com/8568594/224516471-df7e76d5-e5bd-4670-8217-a2c229a84ec9.png)

**Comment by Palleri** [comment]
Hi, I found the reason why.  
This is happening because the dockcheck-slim container has been restarted and not taken down.  
Im trying to figure out how to make this work in the long run.  
But for now a quick fix is to `docker-compose down` the container and bring it up again `docker-compose up -d`  

The cron file is being appended with the new settings every time you restart the container.  

Make sure to check out the new version of dockcheck-web at (DCW) [https://github.com/Palleri/DCW](https://github.com/Palleri/DCW)  
Its even slimmer than the slim version of dockcheck-web haha.
If you dont want the gui to exists on the DCW you can always skip to publish the ports. Unfortunately this version might have the same bug.  I will try to fix it on both dockcheck-slim and DCW.

**Comment by Palleri** [comment]
I found the flaw quite quickly and pushed a new fix to the latest palleri/dockcheck-slim:latest.  
Download the new image and try again to see if its resolved.

**Comment by shape-err** [comment]
Glad that was an easy fix for you! The new image is working well. I didnt have any duplicate messages yesterday and today.
